### PR TITLE
Add label to team, making the ID be 'something else'.

### PR DESCRIPTION
**Pull request by nickygerritsen**
@niemela I know you were tasked to do this but maybe forgot (or didn't have time yet), but we want to test this at NAC, so we first need the spec to have it.

### CODE REVIEW

**Review by deboer-tim — DISMISSED** [review]
Approved, but shouldn't it be non-optional?

**Comment by nickygerritsen** [comment]
> Approved, but shouldn't it be non-optional?

I was wondering the same. I guess this is a field that if you have it, you better have it for all teams right? So then we should make it non optional?

**Comment by deboer-tim** [comment]
> > Approved, but shouldn't it be non-optional?
> 
> I was wondering the same. I guess this is a field that if you have it, you better have it for all teams right? So then we should make it non optional?

Yes, that's what I was assuming.

**Review by niemela — APPROVED** [review]

**Comment by meisterT** [comment]
It's hard for me to understand when to use what of id, label, name and display_name. What gap are we filling with this PR?

**Comment by nickygerritsen** [comment]
The gap we are filling is that for *all other types* we get from the CMS (groups, organizations) we use the ICPC ID as `ID`, which never changes (or shouldn't) but for the teams we use the 'seat number', but we normally don't have that unless we are at the WF. The `label` is very similar (and hence named the same way) as the `label` on a problem.
Basically: ID is internal and no one should really know it (just like problem ID, group ID, etc.) and label is what teams know themselves.

**Pull request merged**
