### PR TITLE
Remove "removing time intervals".

### PR DESCRIPTION
**Pull request by meisterT**
IMO, we should update the spec and reflect reality here. Not all CCSs implement removed time intervals. It is a basically untested feature which is even more dangerous than not having it.

In cases where it really would have been applied (think about fire alarm, bomb threat etc) the contest is impacted in such a way anyway that **if** you want to do something to make it more fair, you can use the "adding penalty time" functionality instead.

### CODE REVIEW

**Comment by meisterT** [comment]
cc @niemela @eldering @clevengr

**Review by nickygerritsen — APPROVED** [review]
I totally agree with this.

**Review by pehrsoderman — APPROVED** [review]

**Comment by eldering** [comment]
I completely support this!

Just a minor correction: the mention of removed intervals at https://github.com/icpc/ccs-specs/pull/52/files#L889 should also be removed.

**Review by eldering — APPROVED** [review]

**Review by nickygerritsen — APPROVED** [review]

**Comment by niemela** [comment]
There has been no progress on this discussion for the past 3 years. Has the arguments for or against evolved any? If not, I would suggest we close this as wontfix. If things change it's easy enough to open it up again.

As one potential argument, I can point out that this feature has still never been used, and for the past several years, I don't even think we have tested it seriously (as we did do for the first several years). Do we think that the current CCS:s implementation of this still work? @clevengr @meisterT (and others)

**Comment by meisterT** [comment]
Instead of keeping it open, can we turn this around and say: please speak up if you want to keep it? (Maybe @clevengr but it's not clear to me)

As a sanity check, we can and maybe should ask the judges what their point of view is. 

If we actually want to keep it we have to make clear how to communicate the removal of a time interval to shadow and other downstream clients.

**Comment by nickygerritsen** [comment]
While shadowing the practice session of GNY2024 a few weeks ago PC^2 "stopped" their clock for 69 seconds without telling DOMjudge.

Their argument was "you can see it in the feed since contest times and absolute times started to drift", but since DOMjudge only stores one of these times, I had to write a small python script to detect where the 69 seconds were "lost" (note they didn't know how long the pause was, I had to determine this) and then insert a removed interval.

The good news is that that worked. The (IMHO) bad news is that indeed there is no proper spec way to tell us, especially when it happens in the future.

I agree with Tobi that we should at least discuss with the judges and if this has to stay decide on how to do it properly

**Comment by deboer-tim** [comment]
Agreed with @niemela that we need to just make a call and close this either way. API support for doing this could be as simple as a pause object with start and optional end - either that's part of a consistent spec, or we remove the reference and agree on the API elsewhere for those that choose to support it as an extension.

**Comment by niemela** [comment]
Closing after discussion on the December 9 meeting of the working group.

The plan is to add a list of removed intervals to the `/state` endpoint to allow downstream systems to detect removed intervals.

**Pull request closed without merging**
