### PR TITLE
In run, judgement_type_id is the verdict of the *run*.

### PR DESCRIPTION
**Pull request by eldering**
Also remove some unnecessary spaces.

### CODE REVIEW

**Review by nickygerritsen — APPROVED** [review]

**Comment by eldering** [comment]
FYI, probably easiest to merge this after #86.

**Review by deboer-tim — APPROVED** [review]
LGTM, but yes, I'm sure Fredrik would appreciate merging first. :)

**Comment by niemela** [comment]
> I'm sure Fredrik would appreciate merging first. :)

Yes, please :)

**Review by niemela — APPROVED** [review]

**Comment by eldering** [comment]
I rebased to fix conflicts, so need 2 approvals again...

**Review by nickygerritsen — APPROVED** [review]

**Review by deboer-tim — APPROVED** [review]

**Review by niemela — APPROVED** [review]

**Pull request merged**
